name: setup
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  async_redux: ^20.0.2

  cupertino_icons: ^1.0.2

  dartx: ^1.2.0

  freezed: ^2.1.0+1

  freezed_annotation: ^2.1.0

  go_router: ^11.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5

  change_app_package_name: ^1.1.0

  flutter_lints: ^2.0.0

  json_annotation: any

  json_serializable: any


flutter:

  uses-material-design: true
